[features]
seeds = false
[programs.localnet]
swap_token = "HyLqP2saUKjQkesmGau9zwRgexPRbWxVq4dDU2KDgabe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
